title : Roberto V치zquez Gonz치lez
tagline: Blog Tagline
author :
  name : Roberto V치zquez Gonz치lez
  email : robertovg24@gmail.com
  github : robertovg
  bitbucket: robertovg
  twitter : robertovg24
  feedburner : gd4sg171gju199lhfh4dd3rvgg
  googleplus: robertovg24
  # Whatever you specify for the linkedin option will be placed after `www.linkedin.com/in/`
  linkedin: robertovg
  flickr: robertovg24
  bitbucket: robertovg
  lastfm: robertovg24




navigation :
  - archive.html  
  - pages.html
  - about.md
